### ISSUE TITLE
Allow header configuration

### ISSUE THREAD

**Issue by Kixiron** [kettle11/devserver#1]
Allow users to configure server headers, either with a command line option, a environmental variable option or a Devserver.toml type of configuration.  
Devserver.toml
```toml
[headers]
Access-Control-Allow-Origin = "*" # Allow CORS
```
CLI
```
devserver --headers Access-Control-Allow-Origin="*"
```
Env
```env
DEVSERVER_HEADERS="Access-Control-Allow-Origin='*'"
```
Out of these (In my opinion at least) the config file option seems the best, as it allows further expansion of configuration in the future
